defaults: &defaults
  docker:
    # specify the version you desire here
    - image: circleci/node:8.0

version: 2
jobs:
  checkout:
    <<: *defaults

    steps:
      - checkout

      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          - v1-dependencies-

      - run:
          name: Install NPM Packages
          command: npm install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

  test:
    <<: *defaults

    steps:
      - run:
          name: Run Unit Tests
          command: npm test
  
  lint:
    <<: *defaults

    steps:
      - run:
          name: Run Linting
          command: npm run lint

  build:
    <<: *defaults

    steps:
      - run:
          name: Build Typescript Code
          command: npm run build

workflows:
  version: 2

  build:
    jobs:
      - checkout

      - test:
          requires:
            - checkout
      
      - lint:
          requires:
            - checkout
      
      - build:
          requires:
            - test
            - lint
